// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntityFrameworkCore.Data.Models;

public partial class Coach
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? TeamId { get; set; }

    public virtual Team Team { get; set; }
}