// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntityFrameworkCore.Data.Models;

public partial class Match
{
    public int Id { get; set; }

    public int HomeTeamId { get; set; }

    public int AwayTeamId { get; set; }

    public DateTime MatchDate { get; set; }

    public virtual Team AwayTeam { get; set; }

    public virtual Team HomeTeam { get; set; }
}