// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntityFrameworkCore.Data.Models;

public partial class Team
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int LeagueId { get; set; }

    public virtual Coach Coach { get; set; }

    public virtual League League { get; set; }

    public virtual ICollection<Match> MatchAwayTeams { get; set; } = new List<Match>();

    public virtual ICollection<Match> MatchHomeTeams { get; set; } = new List<Match>();
}